# Makefile - VxWorks 7 Layer Makefile
#
# @copyright Copyright (C) 2017 Wind River Systems, Inc. All Rights Reserved.
#
# @license Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied."
#
# modification history
# --------------------
# 05oct17,yat  created

PRE_BUILD_DIRS = lib

SHARED_PUBLIC_H_DIRS = h

BUILD_DIRS = lib
BUILD_USER_DIRS = lib

include $(WIND_KRNL_MK)/rules.layers.mk
