# Makefile - Wind River Device Cloud OSAL Makefile
#
# Copyright 2017 Wind River Systems, Inc.
#      
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.
#
# modification history
# -------------------- 
# 05oct17,yat  Created

PRE_BUILD_DIRS = lib

SHARED_PUBLIC_H_DIRS = h

BUILD_DIRS = lib
BUILD_USER_DIRS = lib

include $(WIND_KRNL_MK)/rules.layers.mk
