# Makefile - VxWorks 7 Layer Makefile
#
# Copyright (c) 2017 Wind River Systems, Inc.
#
# The right to copy, distribute, modify, or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.
#
# modification history
# --------------------
# 05oct17,yat  created

PRE_BUILD_DIRS = lib

BUILD_DIRS = lib
BUILD_USER_DIRS = lib

include $(WIND_KRNL_MK)/rules.layers.mk
